---
- name: Download the app bundle
  hosts: localhost
  vars_files:
    - vars/main.yml
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: Download the AAP bundle
      ansible.builtin.include_role:
        name: ./roles/aap_download

- name: Copy the tarball to ther automation controller and install AAP
  hosts: All
  vars_files:
    - vars/main.yml
  become: true
  gather_facts: true
  tasks:
    - name: Run the install role
      ansible.builtin.include_role:
        name: ./roles/aap_install