---
username: "ec2-user"
aap_dir: "/home/{{ username }}/aap_install"
ee_registry_name: "registry.redhat.io"

# Controller install command
controller_install_command: "./setup.sh -- -b --become-user root"
